export enum SystemAction {
  // Browser actions
  BROWSER_INITIALIZING = 'BROWSER_INITIALIZING',
  BROWSER_READY = 'BROWSER_READY',
  BROWSER_CLOSED = 'BROWSER_CLOSED',
  BROWSER_ERROR = 'BROWSER_ERROR',
  BROWSER_CLOSING = 'BROWSER_CLOSING',

  // Navigation actions
  NAVIGATING = 'NAVIGATING',
  NAVIGATION_COMPLETE = 'NAVIGATION_COMPLETE',
  NAVIGATION_ERROR = 'NAVIGATION_ERROR',
  NAVIGATION_SUCCESS = 'NAVIGATION_SUCCESS',

  // DOM actions
  DOM_EXTRACTING = 'DOM_EXTRACTING',
  DOM_READY = 'DOM_READY',
  DOM_ERROR = 'DOM_ERROR',
  DOM_UPDATED = 'DOM_UPDATED',
  EXTRACTING_DOM = 'EXTRACTING_DOM',
  ELEMENT_SELECTED = 'ELEMENT_SELECTED',

  // Screenshot actions
  TAKING_SCREENSHOT = 'TAKING_SCREENSHOT',
  SCREENSHOT_TAKEN = 'SCREENSHOT_TAKEN',
  SCREENSHOT_ERROR = 'SCREENSHOT_ERROR',

  // View actions
  REFRESHING_VIEW = 'REFRESHING_VIEW',
  VIEW_REFRESHED = 'VIEW_REFRESHED',
  REFRESH_ERROR = 'REFRESH_ERROR',

  // Test actions
  GENERATING_TEST = 'GENERATING_TEST',
  TEST_GENERATED = 'TEST_GENERATED',
  RUNNING_TEST = 'RUNNING_TEST',
  TEST_ERROR = 'TEST_ERROR',
  TEST_PASSED = 'TEST_PASSED',
  TEST_FAILED = 'TEST_FAILED',

  // Idle
  IDLE = 'IDLE'
} 